version: "3.7"

services:
  fever-api:
    build: ./api
    container_name: fever-api
    restart: always
    expose:
      - 8080

  temperature-api-nginx:
    build: ./nginx
    container_name: fever-api-nginx
    depends_on:
      - fever-api
    restart: always

  fever-worker:
    build: ./worker
    container_name: fever-worker
    restart: always
    depends_on:
      - fever-api

  fever-database:
    image: postgres:13-alpine
    container_name: fever-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=temperature
    volumes:
      - /home/pi/backup/PostgreSQLVolume:/var/lib/postgresql/data
    expose:
      - 5432

networks:
  default:
    external:
      name: guardian-network
