version: "3.7"

services:

  fever-api:
    build: ./api
    container_name: fever-api
    restart: always
    expose:
      - 8080

  temperature-api-nginx:
    build: ./nginx
    container_name: fever-api-nginx
    depends_on:
      - fever-api
    restart: always

  fever-worker:
    build: ./worker
    container_name: fever-worker
    restart: always
    depends_on:
      - fever-api

networks:
  default:
    external: 
      name: guardian-network